### ISSUE TITLE
Problem with rcpy 

### ISSUE THREAD

**Issue by Jarchilla** [mcdeoliveira/rcpy#11]
Hello Friend. whenever I try to run rc_mip_balance.py. returns errors I have the last stretch image and followed all the installation steps.
rcpy.gpio as gpio File "/usr/local/lib/python3.5/dist-packages/rcpy/gpio.py", line 4, in <module> import gpiod ImportError: libgpiod.so.2: can not open shared object file: No such file or directory Initiating cleanup ... Done with cleanupinstallation.

**Comment by mcdeoliveira** [comment]
You have to install libgpio for gpio related functions to work. Please see the libgpio installation instructions on https://github.com/mcdeoliveira/rcpy. Unfortunately this is not yet bundled with the bbb distribution.
