### ISSUE TITLE
problem while 'libgpiod' make - on beaglebone-blue

### ISSUE THREAD

**Issue by Jabed-Akhtar** [mcdeoliveira/rcpy#16]
after entering '`make`' after building 'libgpiod', the following error is coming ->
_make: *** No targets specified and no makefile found.  Stop._

Description:
I am followint the steps as here 'mcdeoliveira/rcpy'.
Please see the Image to see the files inside the directory...

![image](https://user-images.githubusercontent.com/64619782/138762493-5612fa05-ec2d-444b-b477-6de56fa5fcd5.png)

**Comment by mcdeoliveira** [comment]
Did you run the ./autogen.sh step? You do not have Makefile so it either failed to create one or you did not run it.
